const PT_DICT = {
  // ─── Global & Navigation UI ───
  'Boxing Coach': 'Treinador de Boxe',
  'Calendar': 'Calendário',
  'Workouts': 'Treinos',
  'Schedule': 'Horário',

  // ─── User Selector (HTML entities decoded by browser) ───
  'User 1 (1Yr B→A)': 'Utilizador 1 (1 Ano I→A)',
  'User 2 (6Mo B→A)': 'Utilizador 2 (6M I→A)',
  'User 3 (6Mo B→I)': 'Utilizador 3 (6M I→Int)',
  'User 4 (6Mo I→A)': 'Utilizador 4 (6M Int→A)',

  // ─── Calendar Stats ───
  'Sessions': 'Sessões',
  'Completed': 'Concluído',
  'Hours': 'Horas',
  'Streak': 'Série',

  // ─── Calendar Legend ───
  'Day A – Power': 'Dia A – Potência',
  'Day B – Speed': 'Dia B – Velocidade',
  'Day C – Conditioning': 'Dia C – Condicionamento',
  'Rest': 'Descanso',

  // ─── Calendar Day Cells (generated by JS) ───
  'Day A': 'Dia A',
  'Day B': 'Dia B',
  'Day C': 'Dia C',
  'Power': 'Potência',
  'Speed': 'Velocidade',
  'Cond.': 'Cond.',

  // ─── Calendar Detail Panel ───
  'Rest day': 'Dia de descanso',
  'Active recovery day. Light walk, mobility work, or full rest.': 'Dia de recuperação ativa. Caminhada leve, trabalho de mobilidade ou descanso total.',
  'Mark done': 'Marcar concluído',
  'Start': 'Iniciar',
  '60 min · 3 boxing rounds · punch sounds + combo timer': '60 min · 3 rondas de boxe · sons de golpes + temporizador de combinações',

  // ─── Timer / Workouts View ───
  'Scheduled Workouts': 'Treinos Agendados',
  'Beginner Heavy Bag': 'Saco Pesado: Iniciante',
  'Intermediate Heavy Bag': 'Saco Pesado: Intermédio',
  'Advanced Heavy Bag': 'Saco Pesado: Avançado',
  'HB 1': 'HB 1',
  'HB 2': 'HB 2',
  'HB 3': 'HB 3',
  'Session progress': 'Progresso da sessão',
  'Now training': 'A treinar agora',
  'Select a day': 'Selecione um dia',
  'Combo': 'Combinação',
  'Pause': 'Pausa',
  'Cancel': 'Cancelar',
  'Get Ready!': 'Preparar!',
  'Starting in...': 'A começar em...',
  'Session complete!': 'Sessão concluída!',
  'Great work, fighter!': 'Excelente trabalho, lutador!',
  'Final exercise!': 'Último exercício!',

  // ─── Settings View ───
  'Long-term Training Plan': 'Plano de Treino a Longo Prazo',
  'Select a structured progressive program.': 'Selecione um programa progressivo estruturado.',
  'Classic Weekly Pattern (A/B/C)': 'Padrão Semanal Clássico (A/B/C)',
  '6 Months: Beginner to Advanced (24 weeks)': '6 Meses: Iniciante a Avançado (24 semanas)',
  '6 Months: Beginner to Intermediate (24 weeks)': '6 Meses: Iniciante a Intermédio (24 semanas)',
  '6 Months: Intermediate to Advanced (24 weeks)': '6 Meses: Intermédio a Avançado (24 semanas)',
  '1 Year: Beginner to Advanced (52 weeks)': '1 Ano: Iniciante a Avançado (52 semanas)',
  'Program Start Date': 'Data de Início do Programa',
  'Choose training frequency': 'Escolher frequência de treino',
  '2 Days / Week': '2 Dias / Semana',
  '3 Days / Week': '3 Dias / Semana',
  'Save schedule': 'Guardar horário',
  'Day assignment order': 'Ordem de atribuição dos dias',
  'The order your workout days cycle through the week.': 'A ordem pela qual os seus dias de treino alternam ao longo da semana.',
  'Pick at least 1 training day.': 'Selecione pelo menos 1 dia de treino.',

  // ─── Months ───
  'January': 'Janeiro',
  'February': 'Fevereiro',
  'March': 'Março',
  'April': 'Abril',
  'May': 'Maio',
  'June': 'Junho',
  'July': 'Julho',
  'August': 'Agosto',
  'September': 'Setembro',
  'October': 'Outubro',
  'November': 'Novembro',
  'December': 'Dezembro',

  // ─── Weekday Abbreviations ───
  'Sun': 'Dom',
  'Mon': 'Seg',
  'Tue': 'Ter',
  'Wed': 'Qua',
  'Thu': 'Qui',
  'Fri': 'Sex',
  'Sat': 'Sáb',

  // ─── Phase Labels ───
  'Warm-up': 'Aquecimento',
  'Warm': 'Aque',
  'Boxing': 'Boxe',
  'Boxi': 'Boxe',
  'Strength': 'Força',
  'Stre': 'Forç',
  'Core': 'Core',
  'Cool-down': 'Arrefecimento',
  'Cool': 'Arre',

  // ─── Workout Labels ───
  'Day A – Power': 'Dia A – Potência',
  'Day B – Speed': 'Dia B – Velocidade',
  'Day C – Conditioning': 'Dia C – Condicionamento',

  // ─── Exercise Names ───
  'Jump rope': 'Saltar à corda',
  'Jump rope – fast singles': 'Saltar à corda – saltos rápidos',
  'Jump rope – double unders': 'Saltar à corda – saltos duplos',
  'Arm circles  shoulder rolls': 'Círculos de braços e rotações de ombros',
  'Hip rotations  leg swings': 'Rotações da anca e balanços de pernas',
  'Shadowboxing  footwork': 'Sombra e jogo de pés',
  'Shadowboxing footwork': 'Sombra e jogo de pés',
  'Shadowboxing – 1-2-3 combos': 'Sombra – combinações 1-2-3',
  'Shadowboxing – slips and rolls': 'Sombra – esquivas e rotações',
  'Shadowboxing – full combos': 'Sombra – combinações completas',
  'Shadowboxing – defensive': 'Sombra – ações defensivas',
  'Shadowboxing – full speed': 'Sombra – velocidade máxima',
  'Heavy bag – power shots': 'Saco pesado – golpes de potência',
  'Heavy bag – body shots': 'Saco pesado – golpes ao corpo',
  'Heavy bag – Round 1': 'Saco pesado – Ronda 1',
  'Heavy bag – Round 2': 'Saco pesado – Ronda 2',
  'Heavy bag – Round 3': 'Saco pesado – Ronda 3',
  'Heavy bag – Def. Counters': 'Saco pesado – Contra-ataques defensivos',
  'Heavy bag – Body Snatcher': 'Saco pesado – Ganchos ao corpo',
  'Heavy bag – Burnout': 'Saco pesado – Explosão final',
  'Heavy bag – Tabata': 'Saco pesado – Tabata',
  'Heavy bag – Technical HIIT': 'Saco pesado – HIIT Técnico',
  'Heavy bag – Counters': 'Saco pesado – Contra-ataques',
  'Speed target – rapid jabs': 'Alvo de velocidade – jabs rápidos',
  'HIIT – 10-punch burst  squat': 'HIIT – 10 golpes explosivos e agachamento',
  'Push-ups': 'Flexões',
  'Diamond push-ups': 'Flexões de diamante',
  'Bodyweight squats': 'Agachamentos com peso corporal',
  'Jump squats': 'Agachamentos com salto',
  'Walking lunges': 'Avanços a caminhar',
  'Burpees': 'Burpees',
  'Plank': 'Prancha',
  'Mountain climbers': 'Alpinistas',
  'V-sits': 'Abdominais em V',
  'Russian twists': 'Rotações russas',
  'Hollow body hold': 'Prancha invertida (Hollow Body)',
  'Bicycle crunches': 'Abdominais bicicleta',
  'Cool-down stretch': 'Alongamentos de arrefecimento',
  'Neck & wrist mobilisation': 'Mobilização de pescoço e pulsos',
  'Torso twists': 'Rotações do tronco',
  'Dynamic stretching': 'Alongamentos dinâmicos',
  'Rest between rounds': 'Descanso entre rondas',

  // ─── Exercise Details ───
  'Light pace, stay on toes': 'Ritmo leve, ficar nas pontas dos pés',
  'Full ROM': 'Amplitude total',
  'Both sides': 'Ambos os lados',
  'Move & pivot': 'Mover e rodar',
  'Jab–Cross–Hook': 'Jab – Direto – Gancho',
  'Max power crosses & hooks': 'Diretos e ganchos com potência máxima',
  '12–15 reps': '12–15 repetições',
  '15 reps, drive through heels': '15 reps, impulsionar pelos calcanhares',
  'Tight core, level hips': 'Core firme, ancas niveladas',
  'Fast knees': 'Joelhos rápidos',
  'Full body stretch': 'Alongamento de corpo inteiro',
  'Build up pace': 'Aumentar o ritmo',
  'Loose and fluid': 'Solto e fluido',
  'Defence focus': 'Foco na defesa',
  'Max hand speed': 'Velocidade máxima das mãos',
  'Use all 4 punches': 'Usar todos os 4 golpes',
  '8–10 reps, explosive': '8–10 reps, explosivo',
  '12 each leg': '12 de cada perna',
  '15 reps controlled': '15 reps controladas',
  'Rotate fully each side': 'Rodar completamente para cada lado',
  'Mix singles and doubles': 'Misturar simples e duplos',
  'Leg swings, arm crosses': 'Balanços de pernas, cruzamentos de braços',
  'Slip, roll, pivot focus': 'Foco em esquivar, rolar e rodar',
  '10 all-out alternating punches then squat': '10 golpes alternados a fundo e depois agachamento',
  'Liver & solar plexus hooks': 'Ganchos ao fígado e plexo solar',
  '10–12 reps': '10–12 repetições',
  'Explosive, land soft': 'Explosivo, aterrar suavemente',
  'Lower back pressed down': 'Lombar pressionada contra o chão',
  'Slow and controlled': 'Lento e controlado',
  'L-Jab, R-Cross, L-Hook': 'Jab Esq, Direto Dir, Gancho Esq',
  'Max power R-Crosses & L-Hooks': 'Diretos Dir e ganchos Esq com potência máxima',
  'Max hand speed with L-Jab': 'Velocidade máxima das mãos com Jab Esq',
  'L-Jab, R-Cross, L-Hook, R-Uppercut': 'Jab Esq, Direto Dir, Gancho Esq, Uppercut Dir',
  'L-Hook to Liver & R-Punch to Solar Plexus': 'Gancho Esq ao Fígado e Golpe Dir ao Plexo Solar',

  // ─── Exercise Info (instructions panels) ───
  'Keep elbows tucked in. Stay light on the balls of your feet. Small jumps are enough to clear the rope.':
    'Manter os cotovelos junto ao corpo. Ficar leve nas pontas dos pés. Pequenos saltos são suficientes para passar a corda.',
  'Focus on speed. Small, rapid jumps keeping the core tight and hands spinning the rope quickly.':
    'Foco na velocidade. Saltos pequenos e rápidos mantendo o core firme e as mãos a rodar a corda rapidamente.',
  'Flick the wrists quickly to spin the rope twice per jump. Requires a slightly higher jump and good timing.':
    'Dar um estalo rápido com os pulsos para rodar a corda duas vezes por salto. Requer um salto ligeiramente mais alto e boa coordenação.',
  'Warm up the shoulder joint by making progressive circles forward and backward, then rolling the shoulders.':
    'Aquecer a articulação do ombro fazendo círculos progressivos para a frente e para trás, depois rolar os ombros.',
  'Rotate the hips in circles, then swing each leg forward, backward, and side-to-side to loosen the hips and hamstrings.':
    'Rodar as ancas em círculos, depois balançar cada perna para a frente, para trás e para os lados para soltar as ancas e os isquiotibiais.',
  'Focus on your stance and movement. Move forward, backward, and laterally while maintaining balance.':
    'Foco na postura e no movimento. Mover para a frente, para trás e lateralmente mantendo o equilíbrio.',
  'Maintain a solid base. Step and drag your feet; never cross them. Visualize an opponent.':
    'Manter uma base sólida. Passo e arrasto dos pés; nunca cruzar. Visualizar um adversário.',
  'Jab, Cross, Lead Hook. Ensure full extension on straight punches and pivot your lead foot on the hook.':
    'Jab, Direto, Gancho dianteiro. Garantir extensão total nos golpes retos e rodar o pé dianteiro no gancho.',
  'Practice evasive head movement. Slip outside straight punches and roll (bob and weave) under hooks.':
    'Praticar movimento evasivo de cabeça. Esquivar para fora de golpes retos e rolar (bob and weave) sob ganchos.',
  'Put together all offensive and defensive tools. Be creative and visualize a real sparring round.':
    'Juntar todas as ferramentas ofensivas e defensivas. Ser criativo e visualizar uma ronda real de sparring.',
  'Emphasize your guard, head movement, and footwork retreats. Only throw counter punches.':
    'Enfatizar a guarda, o movimento de cabeça e as retiradas com jogo de pés. Apenas lançar contra-golpes.',
  'Simulate fight pace. Throw punches with max speed while maintaining form and defense.':
    'Simular ritmo de combate. Lançar golpes com velocidade máxima mantendo a forma e a defesa.',
  'Focus on weight transfer and rotation. Sit down on your punches and hit the bag as hard as possible.':
    'Foco na transferência de peso e na rotação. Sentar sobre os golpes e bater no saco o mais forte possível.',
  'Change levels by bending your knees. Dig hooks and uppercuts into the lower half of the bag.':
    'Mudar de nível dobrando os joelhos. Cravar ganchos e uppercuts na metade inferior do saco.',
  'Establish distance with the jab. Use double and triple jabs, both head and body.':
    'Estabelecer a distância com o jab. Usar jabs duplos e triplos, tanto à cabeça como ao corpo.',
  'Focus on the 1-2 combination (Jab-Cross). Ensure the cross lands with power and snapping hip rotation.':
    'Foco na combinação 1-2 (Jab-Direto). Garantir que o direto aterra com potência e rotação rápida da anca.',
  'Integrate the lead hook (1-2-3). Ensure proper body mechanics and bring hands right back to the guard.':
    'Integrar o gancho dianteiro (1-2-3). Garantir mecânica corporal correta e trazer as mãos de volta à guarda.',
  'Visualize an incoming punch. Slip or roll first, then immediately fire a fast combination.':
    'Visualizar um golpe a chegar. Esquivar ou rolar primeiro, depois disparar imediatamente uma combinação rápida.',
  'Use the Jab to blind the opponent, then dig a heavy body hook, followed by an overhand or cross.':
    'Usar o Jab para cegar o adversário, depois cravar um gancho forte ao corpo, seguido de um overhand ou direto.',
  'Non-stop punching. Throw straight 1-2s continuously at the bag as fast as you can.':
    'Golpes sem parar. Lançar 1-2 retos continuamente no saco o mais rápido possível.',
  '20 seconds of maximum effort sprinting on the bag, followed by 10 seconds of complete rest.':
    '20 segundos de esforço máximo no saco, seguidos de 10 segundos de descanso completo.',
  'Combine explosive bursts with active recovery (footwork/jabs). Maintain perfect technique even when tired.':
    'Combinar explosões com recuperação ativa (jogo de pés/jabs). Manter a técnica perfeita mesmo quando cansado.',
  'Work on defending an attack and immediately replying with an uppercut or hook counter.':
    'Trabalhar a defesa de um ataque e responder imediatamente com um uppercut ou gancho de contra-ataque.',
  'Keep your non-punching hand glued to your chin. Snap the jab out and back as fast as possible.':
    'Manter a mão que não golpeia colada ao queixo. Lançar o jab e recolher o mais rápido possível.',
  'Keep a straight line from head to heels. Lower your chest to the floor and press up to full extension.':
    'Manter uma linha reta da cabeça aos calcanhares. Baixar o peito ao chão e empurrar até extensão total.',
  'Place hands close together under your chest forming a diamond shape. Targets the triceps and inner chest.':
    'Colocar as mãos juntas sob o peito formando um diamante. Trabalha os tricípites e peito interior.',
  'Keep your chest up and back straight. Lower your hips until thighs are parallel to the floor.':
    'Manter o peito erguido e as costas retas. Baixar as ancas até as coxas ficarem paralelas ao chão.',
  'Explosively jump up from the bottom of the squat position. Land softly and go immediately into the next rep.':
    'Saltar explosivamente a partir da posição baixa. Aterrar suavemente e ir imediatamente para a próxima repetição.',
  'Step forward and lower your hips until both knees are bent at a 90-degree angle.':
    'Dar um passo em frente e baixar as ancas até ambos os joelhos estarem dobrados a 90 graus.',
  'Drop to a push-up position, perform a push-up, jump feet back to hands, and explosively jump up with hands overhead.':
    'Descer para posição de flexão, fazer uma flexão, saltar os pés para as mãos e saltar explosivamente com as mãos para cima.',
  'Hold a straight body position resting on your forearms. Squeeze your core and glutes.':
    'Manter uma posição corporal reta apoiado nos antebraços. Contrair o core e os glúteos.',
  'From a push-up position, rapidly drive your knees alternating toward your chest.':
    'A partir da posição de flexão, levar rapidamente os joelhos alternadamente em direção ao peito.',
  'Sit balancing on your sit bones. Extend legs and lean back, then bring knees and chest together.':
    'Sentar equilibrado nos ísquios. Estender as pernas e inclinar para trás, depois juntar joelhos e peito.',
  'Sit with feet slightly elevated. Twist your torso side to side, touching the floor on each side.':
    'Sentar com os pés ligeiramente elevados. Rodar o tronco de lado a lado, tocando no chão de cada lado.',
  'Lie on your back, flatten your lower back to the floor, and hover your arms and legs slightly off the ground.':
    'Deitar de costas, pressionar a lombar contra o chão e manter os braços e pernas ligeiramente elevados.',
  'Lie on your back. Alternate bringing your opposite elbow to your knee in a pedaling motion.':
    'Deitar de costas. Alternar trazendo o cotovelo oposto ao joelho num movimento de pedalada.',
  'Gently stretch the neck in all directions and rotate the wrists to prepare for impact.':
    'Alongar suavemente o pescoço em todas as direções e rodar os pulsos para preparar para o impacto.',
  'Stand with a wide stance and twist your upper body left and right to loosen the core and spine.':
    'Ficar de pé com as pernas afastadas e rodar a parte superior do corpo para a esquerda e para a direita para soltar o core e a coluna.',
  'Use movement-based stretches to take joints through their full range of motion.':
    'Usar alongamentos baseados em movimento para levar as articulações através da sua amplitude total.',
  'Perform static stretches holding each position for 15-30 seconds to improve flexibility.':
    'Realizar alongamentos estáticos mantendo cada posição durante 15-30 segundos para melhorar a flexibilidade.',

  // ─── Next Up / Timer Messages ───
  'Next:': 'Próximo:',

  // ─── Timer Round Info ───
  'Round': 'Ronda',
  'of': 'de',
  'Conditioning': 'Condicionamento',
  'Week': 'Semana',
  'Beginner': 'Iniciante',
  'Intermediate': 'Intermédio',
  'Advanced': 'Avançado',

  // ─── Tutorial Links ───
  '▶ Watch Tutorial': '▶ Ver Tutorial',
  'Watch Tutorial': 'Ver Tutorial',

  // ─── Next Up ───
  'Next:': 'Próximo:',
  'Pick at least 1 training day.': 'Selecione pelo menos 1 dia de treino.',
  'Back Care': 'Cuidado Lombar',

  // ─── Technique Library ───
  'Technique': 'Técnica',
  'Video': 'Vídeo',
  'Boxing Technique Library': 'Biblioteca de Técnica',
  'The Jab (1)': 'O Jab (1)',
  'The Cross (2)': 'O Direto (2)',
  'Lead Hook (3)': 'Gancho Avançado (3)',
  'Uppercut (4)': 'Uppercut (4)',
  'Body Shot': 'Golpe ao Corpo',
  'The Slip': 'A Esquiva (Slip)',
  'The most important punch in boxing. A straight lead-hand strike used to gauge distance, blind opponents, and set up power shots.': 
    'O golpe mais importante no boxe. Um ataque reto com a mão da frente usado para medir a distância, cegar oponentes e preparar golpes de potência.',
  'The power punch thrown from the rear hand. It travels a longer distance and utilizes full body rotation.':
    'O golpe de potência lançado com a mão de trás. Percorre uma distância maior e utiliza a rotação total do corpo.',
  'A powerful lateral punch thrown with the front hand. It targets the side of the head or the liver.':
    'Um golpe lateral potente lançado com a mão da frente. Alveja a lateral da cabeça ou o fígado.',
  'A vertical punch used to strike from underneath, typically targeting the chin of an opponent leaning forward.':
    'Um golpe vertical usado para atacar por baixo, tipicamente visando o queixo de um oponente inclinado para a frente.',
  'Punches directed at the torso, specifically the liver (lead side) or solar plexus.':
    'Golpes direcionados ao tronco, especificamente ao fígado (lado dianteiro) ou plexo solar.',
  'A core defensive movement where you move your head slightly off the center line to evade a straight punch.':
    'Um movimento defensivo fundamental onde move a cabeça ligeiramente fora da linha central para evitar um golpe reto.',
  'Keep your chin tucked behind your lead shoulder.': 'Mantenha o queixo encolhido atrás do ombro da frente.',
  'Snap the hand out and back to your face immediately.': 'Dispare a mão e recolha-a para o rosto imediatamente.',
  'Stay light on your feet and avoid leaning forward.': 'Mantenha-se leve nos pés e evite inclinar-se para a frente.',
  'Pivot your back foot like you are "squashing a bug".': 'Rode o pé de trás como se estivesse a "esmagar uma barata".',
  'Ensure your lead hand stays up to protect your face.': 'Garante que a mão da frente fica em cima para proteger o rosto.',
  'Exhale sharply as you throw the punch.': 'Expire bruscamente ao lançar o golpe.',
  'Keep your elbow at a 90-degree angle.': 'Mantenha o cotovelo num ângulo de 90 graus.',
  'Pivot your front foot and rotate your hip aggressively.': 'Rode o pé da frente e gire a anca agressivamente.',
  'Keep your rear hand high on your chin.': 'Mantenha a mão de trás alta no queixo.',
  'Dip your knees slightly before throwing.': 'Dobre ligeiramente os joelhos antes de lançar.',
  'Drive the power from your legs and hips.': 'Impulsione a potência através das pernas e ancas.',
  'Do not drop your hand too low before the strike.': 'Não baixe demasiado a mão antes do golpe.',
  'Bend your knees to change levels; do not just lean over.': 'Dobre os joelhos para mudar de nível; não apenas se incline.',
  'Step slightly off-center to find the angle.': 'Dê um passo ligeiro fora de centro para encontrar o ângulo.',
  'Stay tight and keep your guard up to avoid counters.': 'Mantenha-se fechado e com a guarda alta para evitar contra-ataques.',
  'Small movements are better than big ones.': 'Pequenos movimentos são melhores do que grandes.',
  'Keep your hands up while slipping.': 'Mantenha as mãos em cima enquanto se esquiva.',
  'The Roll (Bob & Weave)': 'A Esquiva (Roll/Pendente)',
  'The Pivot': 'O Pivot',
  'Check Hook': 'Check Hook',
  'Feinting': 'Fintas',
  'The Parry': 'O Desvio (Parry)',
  'Catch & Shoot': 'Pausar e Ripostar (Catch & Shoot)',
  'Defending against hooks and overhands by rolling your head and torso underneath the punch in a "U" motion.':
    'Defender-se de ganchos e cruzados largos rodando a cabeça e o tronco por baixo do golpe num movimento em "U".',
  'Fundamental footwork used to change angles, create openings, and escape pressure or corners.':
    'Trabalho de pés fundamental usado para mudar ângulos, criar aberturas e escapar à pressão ou cantos.',
  'An advanced defensive counter where you throw a lead hook while pivoting away from an aggressive opponent.':
    'Um contra-ataque defensivo avançado onde se lança um gancho da frente enquanto se roda para longe de um oponente agressivo.',
  'The art of deceptive movement to bait a reaction, blind an opponent, or create an opening for a real attack.':
    'A arte do movimento enganador para atrair uma reação, cegar um oponente ou criar uma abertura para um ataque real.',
  'Deflecting a straight punch by tapping it with the palm of your glove, directing it away from your centerline.':
    'Desviar um golpe reto tocando-o com a palma da luva, direcionando-o para fora da linha central.',
  'A classic counter-punching skill where you catch a punch with your glove and fire back immediately.':
    'Uma habilidade clássica de contra-ataque onde se apara um golpe com a luva e se responde imediatamente.',
  'Transfer your weight from one leg to the other during the roll.': 'Transfira o peso de uma perna para a outra durante a rotação.',
  'Do not bend at the waist; use your knees.': 'Não se incline pela cintura; use os joelhos.',
  'Keep your eyes on the opponent even when underneath.': 'Mantenha os olhos no oponente mesmo quando estiver por baixo.',
  'Stay on the ball of your lead foot.': 'Mantenha-se sobre a ponta do pé da frente.',
  'Whip your back leg around to quickly change orientation.': 'Lance a perna de trás para mudar a orientação rapidamente.',
  'Keep your hands up and stay balanced throughout.': 'Mantenha as mãos em cima e o equilíbrio durante todo o movimento.',
  'Time the punch as the opponent moves into your range.': 'Sincronize o golpe enquanto o oponente entra no seu alcance.',
  'The pivot must happen simultaneously with the punch.': 'O pivot deve ocorrer simultaneamente com o soco.',
  'Lead the opponent into where you were, not where you are.': 'Conduza o oponente para onde você estava, não para onde você está.',
  'Use your eyes, hands, and shoulders to sell the fake.': 'Use os olhos, mãos e ombros para vender o movimento falso.',
  'Ensure the feint is subtle but convincing.': 'Garanta que a finta é subtil mas convincente.',
  'Be ready to capitalize on the opening instantly.': 'Esteja pronto para capitalizar a abertura instantaneamente.',
  'Use short, sharp tapping motions.': 'Use movimentos curtos e secos.',
  'Do not reach out; wait for the punch to come to you.': 'Não se estique; espere que o golpe venha até si.',
  'Keep your elbows tucked and stay protected.': 'Mantenha os cotovelos encolhidos e mantenha-se protegido.',
  'Absorption and retaliation should be one fluid motion.': 'A absorção e a retaliação devem ser um movimento fluido.',
  'Keep your feet planted to generate counter-power.': 'Mantenha os pés firmes para gerar potência no contra-golpe.',
  'Always protect the side of your head while shooting back.': 'Proteja sempre a lateral da cabeça enquanto riposta.',
  'The Sprawl': 'O Sprawl',
  'Weighted Shadowboxing': 'Shadowboxing com Pesos',
  'A dynamic conditioning and defensive move used to drop your hips to the floor and evade low attacks or build explosive power.':
    'Um movimento dinâmico de condicionamento e defesa para baixar as ancas até ao chão e evitar ataques baixos ou ganhar explosão.',
  'Shadowboxing while holding light dumbbells (1-2kg) to significantly increase shoulder endurance and punch snap.':
    'Shadowboxing segurando halteres leves (1-2kg) para aumentar significativamente a resistência dos ombros e a velocidade do soco.',
  'Shoot your legs back as far as possible.': 'Atire as pernas o mais para trás possível.',
  'Drop your hips flush to the floor.': 'Baixe as ancas encostadas ao chão.',
  'Explode back up into your fighting stance immediately.': 'Exploda de volta para a posição de combate imediatamente.',
  'Do not go too heavy; the goal is speed and form.': 'Não use demasiado peso; o objetivo é a velocidade e a forma.',
  'Focus on keeping your hands up even when tired.': 'Foque-se em manter as mãos em cima, mesmo quando estiver cansado.',
  'Maintain perfect technique; do not lunge or over-extend.': 'Mantenha a técnica perfeita; não se lance nem estenda excessivamente.',
  'Day D – Ringcraft': 'Dia D – Técnicas de Ringue',
  'Shadowboxing – ringcraft': 'Shadowboxing – Controlo de Ringue',
  'Heavy bag – Feint & Counter': 'Heavy bag – Finta e Contra-ataque',
  'Heavy bag – Check Hooks': 'Heavy bag – Check Hooks (Pivot)',
  'Conditioning – Sprawls': 'Conditioning – Sprawls',
  'Build rhythm': 'Construir ritmo',
  'Pivot & slide': 'Rodar e deslizar',
  'Focus on angles & pivots': 'Foco em ângulos e pivôs',
  'Deceptive entry, then counter': 'Entrada enganosa, depois contra-atacar',
  'Pivot 90 deg while landing hook': 'Rodar 90 graus enquanto lança o gancho',
  'Max speed sprawls': 'Sprawls em velocidade máxima',
  'Deep recovery stretch': 'Alongamento de recuperação profunda',
  'Focus on movement and pivoting. Control the center of the ring, cut off angles, and maintain balance.':
    'Foque-se no movimento e pivot. Controle o centro do ringue, feche ângulos e mantenha o equilíbrio.',
  'Use feints to draw a reaction from the "opponent" (the bag), then slip and fire a sharp counter combination.':
    'Use fintas para atrair uma reação do "oponente" (o saco), depois esquive-se e dispare uma combinação de contra-ataque rápida.',
  'Practice landing the hook while pivoting 90 degrees as the bag moves towards you; stay balanced.':
    'Pratique lançar o gancho enquanto roda 90 graus conforme o saco se move na sua direção; mantenha o equilíbrio.',
  'Drop into a sprawl (hips to floor, legs back) then quickly recover to your fighting stance.':
    'Lance o sprawl (ancas no chão, pernas para trás) e recupere rapidamente para a posição de combate.'
};
